#!/usr/bin/env bash
su vagrant -c 'brew update'
su vagrant -c 'brew tap caskroom/cask'
su vagrant -c 'brew tap caskroom/versions'
su vagrant -c 'brew install wget'
#su vagrant -c 'brew cask install java11'
su vagrant -c 'VERSION=10.0.2; DOWNLOAD_URL="download.java.net/java/GA/jdk10"; JDK="openjdk-${VERSION}_osx-x64_bin.tar.gz"; INSTALL_DIR="/Library/Java/JavaVirtualMachines"; wget http://pc-instru.lpp.polytechnique.fr/setups/openjdk-10.0.2_osx-x64_bin.tar.gz -O /tmp/${JDK}; sudo tar xfz /tmp/${JDK} -C ${INSTALL_DIR}'
su vagrant -c 'brew install qt lcov meson'
su vagrant -c 'brew install python3 objc-codegenutils objc-run'
su vagrant -c 'brew install pkg-config zlib cmake libtiff cfitsio hdf5 gsl clfft pandoc llvm qt5 go'
su vagrant -c 'brew install iltommi/brews/hdf4'
su vagrant -c 'softwareupdate --list'
su vagrant -c 'softwareupdate --install "Command Line Tools (macOS Sierra version 10.12) for Xcode-9.2"'
su vagrant -c 'sudo xcode-select --switch /Library/Developer/CommandLineTools'
